name: Deploy to Remote Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SSH into Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d /var/www/itmohub/.git ]; then
              cd /var/www/itmohub
              git pull
            else
              git clone https://github.com/AndrewKraevskii/itmohub.git /var/www/itmohub
              cd /var/www/itmohub
            fi
            cd /var/www/itmohub
            git pull
            pnpm install
            pnpm run build
            cp package.json build  
            if pm2 show itmohub >/dev/null; then
              pm2 reload itmohub
            else
              pm2 start build/index.js --name itmohub
            fi
