name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pnpm
      run: |
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g pnpm

    - name: Build project
      run: |
        pnpm install
        pnpm run build

    - name: Deploy to server over SSH
      uses: easingthemes/ssh-deploy@v4.1.8
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "/build"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: itmohub
      
      - name: Run site
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: echo "Start running" && cd ~/itmohub/ && node index.js
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
